--liquibase formatted sql
--changeset Nikita:create-tables

DROP TABLE IF EXISTS
    TOKENS,
    REPORTS,
    USERS,
    ROLES,
    PHONE_NUMBER_DATA,
    USERS_ROLES;

CREATE TABLE IF NOT EXISTS ROLES
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name varchar(20) UNIQUE                                  NOT NULL
);

CREATE TABLE IF NOT EXISTS PHONE_NUMBER_DATA
(
    id           uuid        NOT NULL,
    country_code varchar(5)  NOT NULL,
    city_code    varchar(5)  NOT NULL,
    phone        varchar(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS USERS
(
    id                   uuid PRIMARY KEY   NOT NULL,
    username             varchar(20) UNIQUE NOT NULL,
    password             varchar            NOT NULL,
    email                varchar(50) UNIQUE,
    phone_number         varchar(50) UNIQUE NOT NULL,
    phone_number_data_id uuid REFERENCES PHONE_NUMBER_DATA (id),
    name                 varchar(50)        NOT NULL
);

CREATE TABLE IF NOT EXISTS TOKENS
(
    id            uuid PRIMARY KEY                             NOT NULL,
    refresh_token varchar UNIQUE                               NOT NULL,
    token_type    varchar                                      NOT NULL,
    token_purpose varchar                                      NOT NULL,
    remember_me   boolean,
    revoked       boolean,
    expired       boolean,
    user_id       uuid REFERENCES USERS (id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE IF NOT EXISTS REPORTS
(
    id                 uuid    NOT NULL,
    user_id            uuid REFERENCES USERS (id),
    status             varchar NOT NULL,
    report_content     text,
    report_time        timestamp,
    operator_id        uuid REFERENCES USERS (id),
    status_change_time timestamp,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS USERS_ROLES
(
    user_id uuid REFERENCES USERS (id) ON DELETE CASCADE,
    role_id bigint REFERENCES ROLES (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);
